<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Create two equal columns that floats next to each other */

</style>
</head>
<body>
<div class="row main" style="margin-top: 4%;">
  <div class="columni main one" >
     <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/afour.jpg'); ?>" alt="Avatar" class="image123">
     <img style="width: 98%" src="<?php echo $this->getViewFileUrl('Magento_Cms::images/afour1.jpg'); ?>" alt="Avatar" class="image2">
  </div>
  <div class="columni main two" >
        <div class="row main img1" >
            <div class="columni index img1">
             <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/atwo.jpg'); ?>" alt="Avatar" class="imagetwo">
            </div>
            <div class="columni index img2" style="">
              <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/athree.jpg'); ?>" alt="Avatar" class="imagethree">
            </div>
      </div>
      <div class="row main one" >
       <img class="show" src="<?php echo $this->getViewFileUrl('Magento_Cms::images/aone.jpg'); ?>" alt="Avatar" class="image">
      </div>
    </div>
</div>
<div class="row main two">
  
  <div class="columni main three" style="">
        <div class="row main img1">
            <div class="columni index img1">
             <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/atwo.jpg'); ?>" alt="Avatar" class="imagetwo">
            </div>
            <div class="columni index img2" >
              <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/athree.jpg'); ?>" alt="Avatar" class="imagefive">
            </div>
      </div>
      <div class="row main one">
       <img class="show1"  src="<?php echo $this->getViewFileUrl('Magento_Cms::images/aone.jpg'); ?>" alt="Avatar" class="image">
      </div>
    </div>
    <div class="columni main four" style="">
     <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/afour.jpg'); ?>" alt="Avatar" class="image1">
     <img style="width: 98%" src="<?php echo $this->getViewFileUrl('Magento_Cms::images/afour1.jpg'); ?>" alt="Avatar" class="image21">
  </div>
</div>

</body>
</html>