<div class="slider-usp">
  <div data-content-type="row" data-appearance="contained" data-element="main">
    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-video-fallback-src="" data-element="inner" style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 0px;">
    <div data-content-type="html" data-appearance="default" data-element="main" style="border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 0px;" data-decoded="true">
    <div class="js-slick-slider-usp slick-initialized slick-slider"><div class="slick-list draggable">
          <div class="slick-track" style="opacity: 1; width: 1401px; transform: translate3d(0px, 0px, 0px);">
             <div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 447px;">
                <div>
                   <div style="width: 100%; display: inline-block;"><a style="text-decoration: none;" href="/refer-a-friend?situation=USP_block" tabindex="0"><b style="color: gray">Refer a Friend</b><br><span style="color: gray">£20 for a friend, £20 for you</span></a></div></div></div>
                   <div class="slick-slide slick-active1" data-slick-index="1" aria-hidden="false" style="width: 447px;"><div>
                      <div style="width: 100%; display: inline-block;"><a style="text-decoration: none;" href="/customer-reviews" tabindex="0"> 
                          <img class="truble" src="<?php echo $this->getViewFileUrl('Magento_Cms::images/trustpilot.jpg'); ?>" alt="Avatar"><br> <span style="color: gray"><b style="color: gray">Rated Excellent</b> based on over <b>22,500</b> Trustpilot reviews</span></a></div></div></div>
                         <div class="slick-slide slick-active" data-slick-index="2" aria-hidden="false" style="width: 447px;">
                            <div>
                               <div style="width: 100%; display: inline-block;"><a style="text-decoration: none;" href="/klarna" tabindex="0"><b style="color: gray">Buy now, pay later with Klarna</b><br><span style="color: gray">Learn More</span></a>
                               </div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
             </div>
          </div>
  </div>
</div>
<div class="slideshow-container">

    <div class="mySlides">
      <div style=" display: inline-block;"><a style="text-decoration: none;" href="/refer-a-friend?situation=USP_block" tabindex="0"><b style="color: gray;text-transform: uppercase;font-family: gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif;">Refer a Friend</b><br><span style="color: gray;text-transform: uppercase;font-family: gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif;">£20 for a friend, £20 for you</span></a></div>
    </div>

    <div class="mySlides">
      <div style="width: 100%; display: inline-block;"><a style="text-decoration: none;" href="/customer-reviews" tabindex="0"> 
        <img class="truble" src="<?php echo $this->getViewFileUrl('Magento_Cms::images/trustpilot.jpg'); ?>" alt="Avatar"><br> <span style="color: gray;text-transform: uppercase;font-family: gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif;"><b style="color: gray;text-transform: uppercase;font-family: gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif;">Rated Excellent</b> based on over <b>22,500</b> Trustpilot reviews</span></a></div>

    </div>

    <div class="mySlides">
       <div style="width: 100%; display: inline-block;"><a style="text-decoration: none;" href="/klarna" tabindex="0"><b style="color: gray;text-transform: uppercase;font-family: gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif;">Buy now, pay later with Klarna</b><br><span style="color: gray;text-transform: uppercase;font-family: gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif;">Learn More</span></a>
      </div>
    </div>
<a class="prev" onclick="plusSlides(-1)">❮</a>
<a class="next" onclick="plusSlides(1)">❯</a>

</div>


<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  
  slides[slideIndex-1].style.display = "block";  
 
}
</script>
    <div id="nosto-announcement-bar" class="nosto_element nosto-dynamic-placement top-container"><div class="top-container">
   <div class="S2OFFER">
      <div class="offer" style="width:100%; margin-left:auto; margin-right:auto; max-width:1400px;">
         <div style="display:block; margin:6px 0; line-height:0;" class="S2OFFER">
            <div style="background:#d0d1d2; min-height:38px; display:flex; align-items:center; justify-content:center;">
               <div style="flex:3; text-align:center; padding:6px 8px; color:#ffffff; font-family:'Gill Sans',gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif; letter-spacing:0.1em; font-weight:600; font-size:17px; line-height:17px;">INTRODUCTORY OFFER</div>
               <div style="color:#ffffff; font-size:20px;">|</div>
               <div style="flex:4; text-align:center; padding:6px 8px; color:#575756; font-family:'Gill Sans',gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif; letter-spacing:0.1em; font-weight:200; font-size:17px; line-height:17px;"><span style="font-weight:600;">20% OFF</span> YOUR FIRST ORDER (excluding&nbsp;sale&nbsp;items)</div>
               <div style="color:#ffffff; font-size:20px;">|</div>
               <div style="flex:3; text-align:center; padding:6px 8px; color:#ffffff; font-family:'Gill Sans',gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif; letter-spacing:0.1em; font-weight:600; font-size:17px; line-height:17px;">USE INTR10221 AT&nbsp;THE&nbsp;BASKET</div>
            </div>
         </div>
      </div>
   </div>
   <div class="S2OFFERMOB">
      <div style="width:100%; margin-left:auto; margin-right:auto; max-width:1400px;">
         <div style="display:block; margin:6px 0;" class="S2OFFERMOB">
            <div style="background:#d0d1d2; min-height:75px;">
               <div style="text-align:center; padding:15px 0 5px 0; color:#ffffff; font-family:gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif; letter-spacing:0.1em; font-weight:600; font-size:14px; line-height:17px; width:100%;">INTRODUCTORY OFFER</div>
               <div style="text-align:center; padding:0 0 5px 0; color:#575756;  font-family:gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif; letter-spacing:0.1em; font-weight:200; font-size:14px; line-height:17px; width:100%;"><strong>20% OFF</strong> — USE <strong>MOBOCTA</strong> AT&nbsp;BASKET</div>
               <div style="text-align:center; padding:0 0 15px 0; color:#575756;  font-family:gill-sans,Helvetica Neue,Helvetica,Arial,sans-serif; letter-spacing:0.1em; font-weight:200; font-size:10px; line-height:17px; width:100%;">EXCLUDING SALE ITEMS</div>
            </div>
         </div>
      </div>
   </div>
   <style type="text/css" xml="space">
      <!--
         .S2OFFER{display:block}.S2OFFERMOB{display:none}@media only screen and (max-width:768px){.S2OFFER{display:none}.S2OFFERMOB{display:block}}
         -->
   </style>
</div>
</div>