<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
* {
  footer box-sizing: border-box;
}

body {
  
    font-family: baskerville,Georgia,Times New Roman,Times,serif;
      font-style: normal;
    font-weight: 400;
    line-height: 1.9;
    text-transform: none;
     color: #56636c;
    font-size: 1.5rem;
}

.page-footer {
    background-color: #e9eaeb;
    margin-top: auto;
margin-bottom:38px
}
.footer.content {
    border-top: 0px solid #d1d1d1;
    margin-top: 25px;
    padding-bottom: 25px;
    padding-top: 25px;
}

</style>
<style>


.row.footer-info {
    margin-top: 30px!important;
}
/* Create this for links */
.alink.cox , .alink.cox:visited, a, a:visited {
    color: #56636c;
    text-decoration: none;
}
 a.cox {
    background-color: transparent;
}

a:hover .cox {
  color:  #56636c;
}


</style>

</head>
<body>

<div class="row">
  <div class="col-sm-3 ">
    <h4 class="footer-custom-headings">CUSTOMERS</h4>
  <ul>
    <li><a href="#" class="cox">Your Account</a></li>
<li><a href="#" class="cox">Create an Account</a></li>
 <li><a href="#" class="cox">Trade Customers</a></li>
  <li><a href="#"class="cox">Email Sign Up</a></li>
 <li><a href="#" class="cox">Request a Catalogue</a></li>
<li><a href="#" class="cox">Online Catalogue</a></li>
<li><a href="#" class="cox">Feedback</a></li>
<li><a href="#" class="cox">Unsubscribe</a></li>

<li><a href="https://www.coxandcox.co.uk/customer-reviews"><img src="https://www.coxandcox.co.uk/media/wysiwyg/pages/Menu/trustpilot-footer-1.png" alt="Trustpilot"></a></li>
  </ul>


</div>
  <div class="col-sm-3">
    <h4 class="footer-custom-headings">SHOPPING</h4>
    <ul>
 <li><a href="#" class="cox">Gift Vouchers</a></li>
   <li><a href="#" class="cox">Track my Order</a></li>
   <li><a href="#" class="cox">My Order Status</a></li>
   <li><a href="#" class="cox">FAQs</a></li>
   <li><a href="#" class="cox">Klarna FAQs</a></li>
   <li><a href="#" class="cox">Upholstery FAQs</a></li>
<li><a href="#" class="cox">Paint FAQs</a></li>
<li><a href="#" class="cox">Terms & Conditionss</a></li>
<li><a href="#" class="cox">Upholstery Terms & Conditions</a></li>
<li><a href="#" class="cox">Privacy Statement
Our Cookie Use</a></li>
<li><a href="#" class="cox">Our Cookie Use</a></li>
   </ul>
  </div>
  <div class="col-sm-3">
    <h4 class="footer-custom-headings">COX & COX</h4>
  <ul>
    <li><a href="#" class="cox">About</a></li>
<li><a href="#" class="cox">Style Notes Blog</a></li>
 <li><a href="#" class="cox">Your Style</a></li>
  <li><a href="#" class="cox">Careers</a></li>
 <li><a href="#" class="cox">Contact</a></li>
<li><a href="#" class="cox">Press</a></li>
<li><a href="#" class="cox">Sitemap</a></li>
<li><a href="#" class="cox">Customer Reviews</a></li>
<li><a href="#" class="cox">Refer a Friend</a></li>

  </ul>
  </div>
  
<div class="col-sm-2">
    <h4 class="footer-custom-headings">RETURNS</h4>
  <ul>
   <li><a href="#" class="cox">Delivery</a></li>
  <li><a href="#" class="cox">Returns</a></li>
  </ul>
   </div>

 </div>
<div class="row footer-info">

<div class="col-sm-4"><i class="fal fa-phone-alt"></i>
  <p class="phone-text">0333 0333 2123</p>
  <p class="phone-text">8AM - 10AM </p>
</div>
<div class="col-sm-4">
  <i class="fa fa-facebook-official" style="font-size:24px"></i>
  <i class="fa fa-twitter-square" style="font-size:24px"></i>
  <i class="fa fa-instagram" style="font-size:24px"></i>
  <i class="fa fa-pinterest-square" style="font-size:24px"></i>
</div>

<div class="col-sm-4">
  <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/creditcards.png'); ?>">
</div>
</div>
</body>
</html>



